"""
SEO Runtime — GitHub Issue Creator

Creates a GitHub Issue when critical SEO findings require human attention.
Satisfies the spec requirement for a human-review gate:

  SEO Runtime → Detect Issue → Generate Proposed Fix
  → Create Tracking Issue → Human Review Required → Manual Resolution

Issues are INFORMATIONAL only — no code changes are auto-committed.
Every finding that reaches this module requires explicit human action.
"""
import logging
import os
from datetime import datetime

import requests

log = logging.getLogger("seo.github_issue")

_GITHUB_API = "https://api.github.com"


def _headers() -> dict:
    token = os.environ.get("GITHUB_TOKEN", "")
    return {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "SEO-Runtime-Bot/2.0",
    }


def _severity_icon(sev: str) -> str:
    return {"critical": "🔴", "warning": "🟡", "info": "🔵"}.get(sev, "⚪")


def _build_issue_body(
    run_id: str,
    skill_id: int,
    skill_name: str,
    score: int,
    findings: list[dict],
) -> str:
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    critical = [f for f in findings if f.get("severity") == "critical"]
    warnings = [f for f in findings if f.get("severity") == "warning"]
    info = [f for f in findings if f.get("severity") == "info"]

    def _row(f: dict) -> str:
        icon = _severity_icon(f.get("severity", "info"))
        url = (f.get("url") or "—").replace("https://amulyagupta.in", "") or "/"
        rec = f.get("recommendation", "")[:200]
        return (
            f"| {icon} `{(f.get('severity','info')).upper()}` "
            f"| {f.get('title', '—')} "
            f"| `{url}` "
            f"| {rec} |"
        )

    finding_rows = "\n".join(_row(f) for f in findings[:30])

    critical_summary = ""
    if critical:
        items = "\n".join(
            f"- 🔴 **{f.get('title','')}** — `{(f.get('url','') or '').replace('https://amulyagupta.in','') or '/'}`"
            for f in critical
        )
        critical_summary = f"""
## ⚠️ CRITICAL — IMMEDIATE ACTION REQUIRED

{items}
"""

    return f"""# SEO Audit Findings — Skill {skill_id:02d}/23: {skill_name}

> **Auto-generated by SEO Runtime Bot** · {now}
> Run ID: `{run_id}` · Score: **{score}/100**
> No code changes have been auto-applied. Every fix requires human review.

{critical_summary}

## Summary

| Severity | Count |
|----------|-------|
| 🔴 Critical | {len(critical)} |
| 🟡 Warning | {len(warnings)} |
| 🔵 Info | {len(info)} |

## All Findings

| Severity | Issue | URL | Recommendation |
|----------|-------|-----|----------------|
{finding_rows}

## Resolution Instructions

1. Review each critical finding above
2. Implement the recommended fix in a separate feature branch
3. Test the change locally
4. Open a PR targeting `main` with the fix
5. Get human code review before merging
6. Close this issue once all critical findings are resolved

---
*Autonomous SEO Intelligence Platform · amulyagupta.in*
*Next skill will execute automatically at 04:30 AM IST.*
"""


def create_findings_issue(
    run_id: str,
    skill_id: int,
    skill_name: str,
    score: int,
    findings: list[dict],
) -> str | None:
    """
    Create a GitHub Issue summarising critical SEO findings.

    Returns the issue URL on success, None on failure.
    Only called when the run produced at least one critical finding.
    """
    token = os.environ.get("GITHUB_TOKEN", "")
    repo = os.environ.get("GITHUB_REPOSITORY", "")
    if not token or not repo:
        log.warning("GITHUB_TOKEN or GITHUB_REPOSITORY not set — issue creation skipped")
        return None

    critical_count = sum(1 for f in findings if f.get("severity") == "critical")
    title = (
        f"[SEO {score}/100] Skill {skill_id:02d}: {skill_name} "
        f"— {critical_count} critical finding(s) [{datetime.utcnow().strftime('%Y-%m-%d')}]"
    )
    body = _build_issue_body(run_id, skill_id, skill_name, score, findings)

    labels = ["seo-audit", "needs-review"]
    if critical_count > 0:
        labels.append("critical")

    url = f"{_GITHUB_API}/repos/{repo}/issues"
    payload = {"title": title, "body": body, "labels": labels}

    for attempt in range(3):
        try:
            r = requests.post(url, headers=_headers(), json=payload, timeout=20)
            if r.status_code == 201:
                issue_url = r.json().get("html_url", "")
                log.info("GitHub issue created: %s", issue_url)
                return issue_url
            elif r.status_code == 404:
                log.warning(
                    "GitHub issue creation failed (404) — labels may not exist yet. "
                    "Retrying without labels."
                )
                payload.pop("labels", None)
            else:
                log.warning(
                    "GitHub issue creation HTTP %d: %s",
                    r.status_code, r.text[:300],
                )
        except Exception as exc:
            log.warning("GitHub issue creation attempt %d failed: %s", attempt + 1, exc)

    log.error("GitHub issue creation failed after 3 attempts")
    return None
