"""
SEO Report Generator — produces markdown audit reports committed to skill PR branches.

Each skill run writes one report to seo/reports/. The GitHub Actions workflow
commits that file to seo/skill-XX branch and opens a PR for human review.
"""

import json
import os
from datetime import datetime

REPORTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "reports")

SEVERITY_BADGE = {
    "critical": "🔴 CRITICAL",
    "warning":  "🟡 WARNING",
    "info":     "🔵 INFO",
}


def _slug(name: str) -> str:
    return (
        name.lower()
        .replace(" ", "-")
        .replace("&", "and")
        .replace("/", "-")
        .replace("(", "")
        .replace(")", "")
    )[:30].rstrip("-")


def _score_badge(score: int) -> str:
    if score >= 80:
        return f"🟢 {score}/100 — GOOD"
    if score >= 50:
        return f"🟡 {score}/100 — NEEDS WORK"
    return f"🔴 {score}/100 — CRITICAL"


def _findings_section(findings: list[dict], label: str, emoji: str) -> str:
    if not findings:
        return ""
    lines = [f"### {emoji} {label} ({len(findings)})\n"]
    for f in findings:
        title = f.get("title", "Untitled")
        desc = f.get("description", "")
        rec = f.get("recommendation", "")
        url = f.get("url", "")
        evidence = f.get("evidence", "")

        lines.append(f"#### {title}")
        if url:
            lines.append(f"**URL:** `{url}`  ")
        lines.append(f"{desc}")
        if rec:
            lines.append(f"\n> **Fix:** {rec}")
        if evidence:
            lines.append(f"\n> **Evidence:** `{evidence[:200]}`")
        lines.append("")
    return "\n".join(lines)


def generate_skill_report(
    run_id: str,
    skill_id: int,
    skill_name: str,
    score: int,
    findings: list[dict],
    metadata: dict,
    run_date: datetime,
    prev_score: int | None = None,
) -> tuple[str, str]:
    """
    Write a markdown report to seo/reports/ and return (filepath, content).
    Called by runtime.py after every skill execution.
    """
    os.makedirs(REPORTS_DIR, exist_ok=True)

    date_str = run_date.strftime("%Y-%m-%d")
    filename = f"{date_str}-skill-{skill_id:02d}-{_slug(skill_name)}.md"
    filepath = os.path.join(REPORTS_DIR, filename)

    criticals = [f for f in findings if f.get("severity") == "critical"]
    warnings  = [f for f in findings if f.get("severity") == "warning"]
    infos     = [f for f in findings if f.get("severity") == "info"]

    # Delta line
    delta_str = ""
    if prev_score is not None:
        delta = score - prev_score
        arrow = "▲" if delta >= 0 else "▼"
        delta_str = f" ({arrow}{abs(delta):+d} vs previous run)"

    # Actionable recommendations ordered by severity
    actionable = [
        f for f in findings
        if f.get("recommendation") and f.get("severity") in ("critical", "warning")
    ][:10]
    rec_lines = "\n".join(
        f"{i+1}. **[{f['severity'].upper()}]** {f['recommendation']}"
        for i, f in enumerate(actionable)
    ) or "_No high-priority actions required._"

    # PR instruction block
    if criticals:
        pr_action = (
            f"> ⚠️ **{len(criticals)} critical issue(s) found.** "
            "Review the findings below and merge this PR once addressed, "
            "or add comments to discuss."
        )
    elif warnings:
        pr_action = (
            f"> 🟡 **{len(warnings)} warning(s) found.** "
            "Review and merge when convenient."
        )
    else:
        pr_action = "> ✅ No critical or warning issues. Merge to record clean audit."

    # Metadata snippet (truncated)
    meta_json = json.dumps(metadata, indent=2, default=str)[:800]

    content = f"""\
# SEO Audit — Skill {skill_id:02d}/23: {skill_name}

{pr_action}

---

## Overview

| Field | Value |
|---|---|
| **Score** | {_score_badge(score)}{delta_str} |
| **Skill** | {skill_id}/23 — {skill_name} |
| **Date** | {run_date.strftime("%B %d, %Y at %H:%M UTC")} |
| **Run ID** | `{run_id}` |
| **Findings** | 🔴 {len(criticals)} critical · 🟡 {len(warnings)} warnings · 🔵 {len(infos)} info |

---

## Findings

{_findings_section(criticals, "Critical Issues", "🔴")}
{_findings_section(warnings, "Warnings", "🟡")}
{_findings_section(infos, "Informational", "🔵")}

---

## Recommended Actions

{rec_lines}

---

## Runtime Metadata

<details>
<summary>Show metadata</summary>

```json
{meta_json}
```

</details>

---

*Auto-generated by SEO Runtime Bot for [amulyagupta.in](https://amulyagupta.in)*
*Part of the 23-skill autonomous SEO cycle. Merge to acknowledge findings.*
*This PR contains both the audit report and updated dashboard telemetry (`seo/data/`).*
"""

    with open(filepath, "w", encoding="utf-8") as fh:
        fh.write(content)

    return filepath, content
